server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:kafkaapi;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:file:./src/main/resources/db/demodb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: kafkaapi
    password: taxteam
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database-timeout: 3000
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create-drop
#        ddl-auto: update
#        jdbc:
#          batch_size: 500
  h2:
    server:
      properties:
        webAllowOthers: true
    console:
      enabled: true